dataset:
  modalities:
  - rgb
  - dsm
  name: DFC2023S
  splits:
  - train
  - valid
  - test
  type: urban_planning
evaluation:
  depth_cap: 80.0
  mask_invalid: true
  metrics:
  - mae
  - rmse
  - abs_rel
  - sq_rel
  - delta_1.25
  - delta_1.25^2
  - delta_1.25^3
  min_depth: 0.1
inference:
  batch_size: 1
  depth_range:
  - 0
  - 80
  depth_scale: 256.0
  output_format: png
  overlap_handling: average
model:
  architecture: ResNet101
  deploy_path: models/KITTI/deploy.prototxt
  model_path: models/KITTI/cvpr_kitti.caffemodel
  pretrained: true
  type: DORN_KITTI
preprocessing:
  crop_method: sliding_window
  crop_size:
  - 513
  - 385
  crop_stride: 256
  pixel_means:
  - 103.0626
  - 115.9029
  - 123.1516
  resize_method: linear
  target_size:
  - 513
  - 385
