dataset:
  modalities:
  - rgb
  - dsm
  name: Generic_Outdoor
  splits:
  - train
  - valid
  - test
  type: outdoor_depth
evaluation:
  depth_cap: 100.0
  metrics:
  - mae
  - rmse
  - abs_rel
  - sq_rel
  min_depth: 0.1
inference:
  batch_size: 1
  depth_range:
  - 0
  - 100
  depth_scale: 256.0
  output_format: png
model:
  architecture: ResNet101
  deploy_path: models/KITTI/deploy.prototxt
  model_path: models/KITTI/cvpr_kitti.caffemodel
  pretrained: true
  type: DORN_KITTI
preprocessing:
  crop_method: center
  crop_size:
  - 513
  - 385
  pixel_means:
  - 103.0626
  - 115.9029
  - 123.1516
  resize_method: linear
  target_size:
  - 513
  - 385
